steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kuberneteskevin21/kubernetesworkshop21:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kuberneteskevin21/kubernetesworkshop21:$COMMIT_SHA']
- name: 'kevinsimper/render'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
      /render -f /workspace/deployment.yaml -var sha=$COMMIT_SHA -o /workspace
      cat /workspace/workspace/deployment.yaml
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '/workspace/workspace/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west4-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=kevin'
