steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/kuberneteskevin21/kubernetesworkshop21:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/kuberneteskevin21/kubernetesworkshop21:$COMMIT_SHA']
