apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: kevinkubernetes
  name: kevinkubernetes
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: kevinkubernetes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kevinkubernetes
    spec:
      containers:
      - image: gcr.io/kuberneteskevin21/kubernetesworkshop21:cf11a54d224e3b12e5be6a6ef54047c2850c5ccf
        imagePullPolicy: IfNotPresent
        name: kevinkubernetes
        ports:
        - containerPort: 9000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: kevinkubernetes
  name: kevinkubernetes
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32666
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    run: kevinkubernetes
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
data:
  mysqlpassword.txt: dmVyeXNlY3JldHBhc3N3b3Jk
kind: Secret
metadata:
  name: mysqlpassword
type: Opaque
